### PR TITLE
Require python 3.6 properly

### PR DESCRIPTION
**Pull request by felixonmars**
`>=3.5` still supports 3.5.

### CODE REVIEW

**Comment by PythonCoderAS** [comment]
PRAW and PRAWcore still supports 3.5. This is intentional.

**Comment by bboe** [comment]
Thanks, I missed that piece.

Can you actually change it to `python_requires="~=3.6"`? That way we don't assume support for python 4 incase there are breaking changes there.

**Comment by felixonmars** [comment]
Sure, updated :)

**Comment by bboe** [comment]
Thanks! You're awesome! 🎆

**Pull request merged**
