### PR TITLE
Allow passing custom Session class to Requestor

### PR DESCRIPTION
**Pull request by elnuno**
I'm using cachecontrol with PRAW and being able to pass a custom Session would eliminate the need to subclass Requestor just to wrap/tinker with the session.

### CODE REVIEW

**Comment by bboe** [comment]
Great PR. One question, might it make sense to pass the session optionally instead of the class? That would give the caller the flexibility to use an existing session, or explicitly create a new session.

**Comment by elnuno** [comment]
Yes, being able to pass a session is way more flexible, as you can configure it beforehand and the current code doesn't actually pass any arguments on Session creation. 


Would this simple design work? (I'll work on doc change and a test too) 
```diff
-        self._http = requests.Session()
+        self._http = session or requests.Session()
```

**Comment by bboe** [comment]
Yes, your approach should suffice.

**Comment by bboe** [comment]
Also, while you're at it please add yourself to AUTHORS.rst. And it would be fantastic if you could add an unreleased section to the changelog along with the update. Similar to how it was added here:

https://github.com/praw-dev/prawcore/commit/d30fcf8b9b5668ca92073d8af677a29e2ae09b54

Thanks!

**Comment by elnuno** [comment]
Changed the approach to the simpler, more powerful one you suggested. Added to changelog and a simple example. I'm not too sure about the example or the test, suggestions welcome :)

**Comment by bboe** [comment]
Great work!

**Pull request merged**
