### PR TITLE
WorkInProgress: Support both sync and async calls at the same time

### PR DESCRIPTION
**Pull request by vikramaditya91**
As discussed briefly in the [issue #1515 (praw)](https://github.com/praw-dev/praw/issues/1515), I would like to work on supporting both sync and async functionalities in praw without having to rewrite/duplicate async code in another package.

This is a short preview into how I think the target can be achieved.
I wanted to know what the core developers thought of this, and if it makes sense to continue working in this direction?

### CODE REVIEW

**Comment by jarhill0** [comment]
Hi @vikramaditya91,

> I wanted to know what the core developers thought of this, and if it makes sense to continue working in this direction?

I think that, in principle, it would be nice for PRAW to support asynchronous operations. Because so much of what PRAW does is based on network communication, async programming could fit right in. One use-case that stands out to me is that I know some people like to make Discord bots that pull from Reddit using PRAW, and when they use the async [discord.py](https://github.com/Rapptz/discord.py) framework, they would benefit from an async PRAW as well.

That said, I must admit that I am skeptical that these changes can be integrated into PRAW and prawcore without disrupting the existing interfaces. As far as I am aware (and I may be mistaken), a method or function in Python cannot be both synchronous and asynchronous. So, to add async support to PRAW, we would have to either duplicate all methods (and possibly all classes) or change all synchronous methods to async methods. Neither of those seems like a good course of action to me:
- duplication makes using PRAW much more confusing and makes developing it more perilous because there will be separate parts to keep in sync
- switching everything to async is overly disruptive, particularly to use-cases that are already bound by the Reddit rate limit and so will not benefit from async operations

Ultimately, I don't think that the tradeoffs of adding async will be worth it. If it can be done in a minimally invasive way that doesn't take away from the current state of things, my opinion on this would likely change. Of course, please correct me on whatever I have missed or misunderstood. And I appreciate that you are thinking about this and working on it.

Lastly, I'm going to tag @bboe (the author of PRAW) to ask his thoughts on this.

**Comment by vikramaditya91** [comment]
Hi @jarhill0 

Thank you for your very detailed response and your ideas on this.

I agree with you that asynchronous operations cannot be integrated into prawcore without creating new classes, new methods, etc. However, in my opinion there is a need for an async praw as displayed by the the repositories ([asyncpraw](https://github.com/LilSpazJoekp/asyncpraw) and [aPRAW](https://github.com/Dan6erbond/aPRAW)) that you had pointed out earlier.

> duplication makes using PRAW much more confusing and makes developing it more perilous because there will be separate parts to keep in sync

There is going to be a certain level of code duplication, however, it can be minimized. And in my opinion maintaining asynnc praw and sync praw in the same repository should be easier to maintain that having entirely two different repos.

> switching everything to async is overly disruptive, particularly to use-cases that are already bound by the Reddit rate limit and so will not benefit from async operations
As far as I know, the reddit rate limit is 30 requests per minute (correct me if I am wrong). Without an async, I suspect a user would be able to get around a maximum of ~10-15 requests per minute. 

My idea was to create new classes/methods for Async operations while keeping the functionality of the Sync Classes. 
For instance, 
- a new class `RequestorAsync` is created which mirrors the `Requestor` but does it in an asynchronous way. 
- The `Requestor` class is however refactored to avoid code duplication between `RequestorAsync` and `Requestor`


However, if the core developers do not think async is worth considering in PRAW in its current state, my arguments would of course be invalid.

**Comment by jarhill0** [comment]
Thanks for your response! 😁

> As far as I know, the reddit rate limit is 30 requests per minute (correct me if I am wrong). Without an async, I suspect a user would be able to get around a maximum of ~10-15 requests per minute.

I believe the rate limit is 60 requests per minute (per [this](https://github.com/reddit-archive/reddit/wiki/API)). The amount that you can get from it depends on the speed of your internet connection. I wrote a script to test this — [here's the link](https://gist.github.com/jarhill0/384458102d89993b41e62804d445c5ff) — that runs for 60 seconds and then exits and prints the result. Make sure to run it on an account that doesn't have any other API client connected at the same time. If you get a negative number as a result then that probably means the ratelimit reset while you were testing. If you try again, it should be fine.

Running on my personal computer and home internet connection, I got 52, then 55, then 57, then 60, then 61, then 62 requests per minute (over six trials). To me this indicates that with a fast enough connection, the bottleneck is not the network but the rate limit.

For programs that spend most of their time doing Reddit-related things (like Reddit bots), an async PRAW won't speed anything up since they're already being bottlenecked by the Reddit API ratelimit. Of course, there would still be benefits to other types of programs that have heavy async workloads already (because they would no longer waste time with a blocking call into PRAW), but I'd like these benefits not to be at the expense of the rest of the PRAW users.

> a new class `RequestorAsync` is created which mirrors the `Requestor` but does it in an asynchronous way.

This is where I'm somewhat confused, so perhaps you can clarify.

If `RequestorAsync` mirrors `Requestor`, will the `request` method be `async` or not? At the moment you seem to have made it `async`. Based on my (limited) experience with async programming in Python, you can only call an `async` method from another `async` method. So, any method that wants to call the `async` `request` method must itself be `async`, and then any method calling those `async` methods must themselves be `async`, and so on. In this way it seems we would require all of PRAW to be `async` (or that we wholly duplicate PRAW and make all the new methods `async`).

At the same time, the `request` method in the original `Requestor` class is synchronous and should probably stay that way. 

So I'm having trouble seeing how this feature can be added without creating two versions of PRAW (or two separate sets of methods and classes), one which expects `request` to be `async` and one which expects it to be synchronous.


> However, if the core developers do not think async is worth considering in PRAW in its current state, my arguments would of course be invalid.

I think that @bboe should have the final word on this (whenever he gets a chance to look). Personally I have doubts (as you can see), but I don't want to write this off yet because it would be valuable if it fits in right.

**Comment by bboe** [comment]
Hi @vikramaditya91,

Thanks for the interest in PRAW and prawcore and the efforts to bring async to the project. I love the idea of there being a well supported Python async package for Reddit's API, and I am happy to lend the praw-dev namespace for such a package. However, my concerns are similar to @jarhill0's. I feel that trying have a package that works both synchronously and asynchronously is likely to be a pain to maintain, and also rather confusing for end-users. If it were easy, I would guess the `requests` package would have already done it.

While I'm not completely closing the door to such an approach, I'd want to see both a well supported package that supports both, and a prototype of what PRAW might look like when supporting both. With respect to prawcore, I still feel that this package should be as simple as possible, so making a separate asyncprawcore would be ideal, with PRAW hypothetically being the glue between which core module to leverage.

To add to that, whoever creates such packages, or adds such support, I'd expect to continue to maintain them. PRAW, as is, already takes up a decent amount of time so I'm a bit ambivalent to drastically increasing it scope.

**Comment by vikramaditya91** [comment]
Thanks again @bboe and @jarhill0 for the very comprehensive explanations and ideas.

@jarhill0 Thanks for the script to check the rate of requests.
The idea was to do it as follows:
- The new method: `RequestorAsync.request` should be asynchronous
- The original method `Requestor.request`'s would still be synchronous (but it would be refactored)

Everyone who uses `Requestor.request` would call it synchronously. But users of `RequestorAsync.request` would be calling it from `async`/`await`ed methods.

So almost every class would have to be duplicated if it involves async operations.
My idea was that the code duplication would be there, but with the right Base classes, this could be minimized.


@bboe I agree maintaining and using an async+sync classes on prawcore is going to be a bit of a hassle. However, I believe that maintaining two different repos is going to be more effort than maintaining "similar"ly duplicated code in the same repo.
However, I also do understand that the user could be overwhelmed with such things.
I very much like the idea of having a prawcore and asyncprawcore with PRAW ideally supporting them both.

Here is how I see this going forward:

Step 1. Work is started on creating on an asynchronous prawcore. The [asyncprawcore](https://github.com/LilSpazJoekp/asyncprawcore) of @PythonCoderAS seems to be already doing a good job (however might need some updating). This could be added to the praw-dev workspace on @PythonCoderAS's wish. It would need maintaining though which I can take up if @PythonCoderAS does not want to. 

2. Once step 1 is completed and robustified with test cases, I can start work on getting PRAW to be able to handle async calls too.

Please let me know what you think about this idea. Looking forward to working on this!

**Comment by PythonCoderAS** [comment]
@vikramaditya91 I am not the owner of asyncpraw, if you want to be part of that repo, contact @LilSpazJoekp . The biggest problem of maintaining a separate fork is that while it's not all too hard to port the existing code, it becomes hard to then port all future developments from the main repo.

**Comment by vikramaditya91** [comment]
@PythonCoderAS

In one of your earlier comments you had said that you had started progress on it, that is why I thought that it was your alter-account
@vikramaditya91 I had started progress on https://github.com/LilSpazJoekp/asyncprawcore, months ago, ...
_Originally posted by @PythonCoderAS in https://github.com/praw-dev/praw/issues/1515#issuecomment-633139685_

> The biggest problem of maintaining a separate fork is that while it's not all too hard to port the existing code, it becomes hard to then port all future developments from the main repo.
This is precisely why I was pushing to have both Sync and Async operations inside prawcore. But there is some resistance to this idea.

**Comment by LilSpazJoekp** [comment]
I think having 2 different code bases would be easier to maintain than having it together. With that said, my [asyncprawcore](https://github.com/LilSpazJoekp/asyncprawcore) and [asyncpraw](https://github.com/LilSpazJoekp/asyncpraw) are functional as I am currently using them in a few of my discord bots. However, I have not kept up on the new features that have been added to praw in a while. @bboe has expressed interest in bringing both into the praw-dev namespace once we have passing tests for prawcore and subsequently praw. I do want to stress that the goal of the async capability is for async environments and not for speed.

Right now, the following things need to be done for both asyncprawcore and asyncpraw:

- Merge any new changes from the non async repo
- Write passing tests
- Update documentation to describe the async aspect of it

**Comment by vikramaditya91** [comment]
Hey @LilSpazJoekp, sorry I had been a bit busy lately too.
I would like to get started with asyncprawcore over the coming weekend. 

Please do add me as a collaborator the asyncprawcore repo.

**Comment by LilSpazJoekp** [comment]
> Hey @LilSpazJoekp, sorry I had been a bit busy lately too.
> I would like to get started with asyncprawcore over the coming weekend.
> 
> Please do add me as a collaborator the asyncprawcore repo.

Done. I also added you to asyncpraw as well.

**Comment by PythonCoderAS** [comment]
@vikramaditya91 Can I close this PR?

**Comment by LilSpazJoekp** [comment]
I would say so because we have asyncprawcore now.

**Pull request closed without merging**
