### PR TITLE
Allow newer testfixtures versions

### PR DESCRIPTION
**Pull request by dotlambda**
Testfixtures 6.0.0 works fine.

### CODE REVIEW

**Comment by bboe** [comment]
Thanks for verifying that 6 works. Can you change it to `<7` in the event 7 does something backwards incompatible?

**Comment by dotlambda** [comment]
@bboe Done. However, this will probably need to be updated quite often. If testfictures upgrades didn't represent a problem in the past, I'd consider dropping the upper bound in order to reduce the necessary amount of work for downstream packagers.

**Comment by bboe** [comment]
Thanks! Question, do downstream packagers include test packages when packaging? Seems unnecessary, but then again, I'm not involved in that process at all.

**Comment by dotlambda** [comment]
At https://github.com/NixOS/nixpkgs, the build process of most python packages includes tests. That way, we can do automatic upgrades and see if anything breaks.

**Pull request merged**
